### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Arkenstone007** [nicolas-lang/Factorio.SpaceScienceDelivery#1]
I get this error when loading. I assume it is a conflicting mod as it was working fine before I added new ones this morning.

![Factorio mod list 5](https://user-images.githubusercontent.com/93827370/140611614-dfcb0dd4-8a60-4ed1-a71d-793e83a7c495.png)
![Factorio mod list 4](https://user-images.githubusercontent.com/93827370/140611615-cf2d2ab9-07f1-4656-896e-768debbf675c.png)
![Factorio mod list 3](https://user-images.githubusercontent.com/93827370/140611616-bdf9d741-c7b1-4565-89bf-73361f30d159.png)
![Factorio mod list 2](https://user-images.githubusercontent.com/93827370/140611617-745f8d47-e0aa-480d-ae9c-299c778da154.png)
![Factorio mod list 1](https://user-images.githubusercontent.com/93827370/140611618-46524111-1be8-4124-9667-156bef1ab493.png)
![Space Science delivery error](https://user-images.githubusercontent.com/93827370/140611619-b581075f-f966-431c-9a79-484a6caf6a14.png)

**Comment by nicolas-lang** [comment]
It seems to fail at `log(item.name .. " --> " .. itemBoxName .. "(" .. (item.icon or item.icons[0]) .. ")")` which would mean either an item has no name or no icon. I would assume it is the icon as name is a mandatory attribute.
Would you please post part of your factorio log file (https://wiki.factorio.com/Log_file) only the part near the error is relevant

**Comment by Arkenstone007** [comment]
This should be the relevant complete section as it might be more than one item as there is this error at the end.  28.571 Error ModManager.cpp:1577: Error in assignID: recipe-category with name 'crafting' does not exist.

28.224 Loading mod nco-SpaceScienceDelivery 0.0.3 (data-final-fixes.lua)
  28.225 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:14: automation-science-pack --> crate-of-automation-science-pack(__base__/graphics/icons/automation-science-pack.png)
  28.225 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-automation-science-pack to  productivity-module limitations
  28.225 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-automation-science-pack to  productivity-module-2 limitations
  28.225 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-automation-science-pack to  productivity-module-3 limitations
  28.225 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-automation-science-pack to  productivity-module-4 limitations
  28.225 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-automation-science-pack to  productivity-module-5 limitations
  28.225 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-automation-science-pack to  productivity-module-6 limitations
  28.225 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-automation-science-pack to  productivity-module-7 limitations
  28.225 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-automation-science-pack to  productivity-module-8 limitations
  28.225 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-automation-science-pack to  productivity-module-9 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:108: tech not found
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:113: automation-science-pack,recipe found,non-space,box found
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:14: logistic-science-pack --> crate-of-logistic-science-pack(__base__/graphics/icons/logistic-science-pack.png)
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-logistic-science-pack to  productivity-module limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-logistic-science-pack to  productivity-module-2 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-logistic-science-pack to  productivity-module-3 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-logistic-science-pack to  productivity-module-4 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-logistic-science-pack to  productivity-module-5 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-logistic-science-pack to  productivity-module-6 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-logistic-science-pack to  productivity-module-7 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-logistic-science-pack to  productivity-module-8 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-logistic-science-pack to  productivity-module-9 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:113: logistic-science-pack,recipe found,non-space,box found
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:14: chemical-science-pack --> crate-of-chemical-science-pack(__base__/graphics/icons/chemical-science-pack.png)
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-chemical-science-pack to  productivity-module limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-chemical-science-pack to  productivity-module-2 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-chemical-science-pack to  productivity-module-3 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-chemical-science-pack to  productivity-module-4 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-chemical-science-pack to  productivity-module-5 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-chemical-science-pack to  productivity-module-6 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-chemical-science-pack to  productivity-module-7 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-chemical-science-pack to  productivity-module-8 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-chemical-science-pack to  productivity-module-9 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:113: chemical-science-pack,recipe found,non-space,box found
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:14: military-science-pack --> crate-of-military-science-pack(__base__/graphics/icons/military-science-pack.png)
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-military-science-pack to  productivity-module limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-military-science-pack to  productivity-module-2 limitations
  28.226 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-military-science-pack to  productivity-module-3 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-military-science-pack to  productivity-module-4 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-military-science-pack to  productivity-module-5 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-military-science-pack to  productivity-module-6 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-military-science-pack to  productivity-module-7 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-military-science-pack to  productivity-module-8 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-military-science-pack to  productivity-module-9 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:113: military-science-pack,recipe found,non-space,box found
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:14: production-science-pack --> crate-of-production-science-pack(__base__/graphics/icons/production-science-pack.png)
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-production-science-pack to  productivity-module limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-production-science-pack to  productivity-module-2 limitations
 28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-production-science-pack to  productivity-module-3 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-production-science-pack to  productivity-module-4 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-production-science-pack to  productivity-module-5 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-production-science-pack to  productivity-module-6 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-production-science-pack to  productivity-module-7 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-production-science-pack to  productivity-module-8 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-production-science-pack to  productivity-module-9 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:113: production-science-pack,recipe found,non-space,box found
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:14: utility-science-pack --> crate-of-utility-science-pack(__base__/graphics/icons/utility-science-pack.png)
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-utility-science-pack to  productivity-module limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-utility-science-pack to  productivity-module-2 limitations
 28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-utility-science-pack to  productivity-module-3 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-utility-science-pack to  productivity-module-4 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-utility-science-pack to  productivity-module-5 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-utility-science-pack to  productivity-module-6 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-utility-science-pack to  productivity-module-7 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-utility-science-pack to  productivity-module-8 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:82: added recipe pack-crate-of-utility-science-pack to  productivity-module-9 limitations
  28.227 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:113: utility-science-pack,recipe found,non-space,box found
  28.231 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:14: space-science-pack --> crate-of-space-science-pack(__base__/graphics/icons/space-science-pack.png)
  28.231 Script @__nco-SpaceScienceDelivery__/data/register_recipes.lua:113: space-science-pack,recipe found,non-space
  28.235 Error ModManager.cpp:1577: Failed to load mod "nco-SpaceScienceDelivery": __nco-SpaceScienceDelivery__/data/register_recipes.lua:14: attempt to concatenate a nil value
stack traceback:
               __nco-SpaceScienceDelivery__/data/register_recipes.lua:14: in main chunk
               [C]: in function 'require'
               __nco-SpaceScienceDelivery__/data-final-fixes.lua:1: in main chunk
  28.237 Loading mod core 0.0.0 (data.lua)
  28.522 Checksum for core: 114548386
  28.571 Error ModManager.cpp:1577: Error in assignID: recipe-category with name 'crafting' does not exist.

**Comment by nicolas-lang** [comment]
it should be fixed in the new release, please test.
