### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by OvermindDL1** [nicolas-lang/Factorio.SpaceScienceDelivery#2]
Mod had been working fine.  SE updated today, now it launches with this error:

```lua
 295.332 Mods to disable:Failed to load mods: __nco-SpaceScienceDelivery__/data/register_recipes.lua:14: attempt to concatenate a nil value
stack traceback:
	__nco-SpaceScienceDelivery__/data/register_recipes.lua:14: in main chunk
	[C]: in function 'require'
	__nco-SpaceScienceDelivery__/data-final-fixes.lua:1: in main chunk

Mods to be disabled:
• nco-SpaceScienceDelivery (0.0.3)
```

**Comment by nicolas-lang** [comment]
Thank's for the report, I'll try to resolve this... please provide:
- factorio-current.log
- mod-list.json

You seem to be crashing on 
```
local txt = item.name
txt = txt .. ",recipe found"
```
which is very confusing since "name" is a [mandatory attribute](https://wiki.factorio.com/PrototypeBase#name) of the prototype

**Comment by OvermindDL1** [comment]
[info.zip](https://github.com/nicolas-lang/Factorio.SpaceScienceDelivery/files/7775202/info.zip)

A couple other mods did also update, though unsure what would cause such a change as the others didn't do anything with SE.

**Comment by OvermindDL1** [comment]
For note, line 14 here is:
```lua
log(item.name .. " --> " .. itemBoxName .. "(" .. (item.icon or item.icons[0]) .. ")")
```
And if `item.name` were `nil` it would have crashed before this on line 12 of `itemBoxName = "crate-of-" .. item.name`, so likely it's just not handling the case where there is no icon (both `icon` and `icons[0]` are allowed to be `nil`, even at the same time, so probably just need another ` or ""` or so in that parenthesis).

**Comment by nicolas-lang** [comment]
it should be fixed in the new release, please re-test.

**Comment by OvermindDL1** [comment]
Updated server again and it does indeed work, thanks much!
