### ISSUE TITLE
Error during loading

### ISSUE THREAD

**Issue by BleidcL** [nicolas-lang/Factorio.SpaceScienceDelivery#3]
Hi,

Since SE last update the Space Science Delivery Mod stop working and gives an error during loading screen.

I attached a screenshot of the error.

Thanks for the amazing mod
![2022-01-07 01 03 12](https://user-images.githubusercontent.com/97270805/148489789-27e71d62-1a0b-4a00-9a32-5293b108e84c.png)
.

**Comment by nicolas-lang** [comment]
Should be a simple fix... I'll look into it.

**Comment by nicolas-lang** [comment]
New release will be published later today, the fix has shown another issue with space-manufacturing which also needs fixing
