### ISSUE TITLE
cant load saves with new version

### ISSUE THREAD

**Issue by xXParryXx** [nicolas-lang/Factorio.SpaceScienceDelivery#5]
so i just recently updated to the .6 verstion from .5 and as im loading up my game i got failed to load.
Failed to load mods:
__nco-SpaceScienceDelivery__/data/register_recipies.lua:8 attempted to index local 'recipe' (a nil value)
stack traceback:
__nco-SpaceScienceDelivery__/data/register_recipies.lua:8 in main chunk
[C]: in function 'require'
__nco-SpaceScienceDelivery__/data_final-fixes.lua:1 in main chunk

**Comment by nicolas-lang** [comment]
Thanks for the report, I'll have a look right away.
