### ISSUE TITLE
Realistic Fusion Power Antimatter Science Packs no longer deliverable in latest version

### ISSUE THREAD

**Issue by OvermindDL1** [nicolas-lang/Factorio.SpaceScienceDelivery#6]
Realistic Fusion Power Antimatter Science Packs no longer deliverable in latest version released today.  Loading the game removed those items and recipes.  I'm thinking removing the dependency on se-postprocess moved it too early in loading, perhaps it needs an optional dependency on the Realistic Fusion Power mod to move it back after?

**Comment by nicolas-lang** [comment]
Can you post a link to the related mod in question, I should be able to have a look tomorrow.

**Comment by OvermindDL1** [comment]
https://mods.factorio.com/mod/RealisticFusionPower

It has SE integration and adds the `Antimatter Science pack`, which used to be deliverable prior to the update earlier today.

**Comment by nicolas-lang** [comment]
Ok, I'll have a look tomorrow.
If you could possibly test if the optional dependency would help it would be much appreciated.

**Comment by OvermindDL1** [comment]
I'm already away from this but I'll try to get back to the computer this evening, however I'm 90% sure it will fix the issue even if I can't get back, I checked the logs and the loading order did have this mod load after RFP, however the latest log shows it loading before RFP now, and this mod in [this file](https://github.com/nicolas-lang/Factorio.SpaceScienceDelivery/blob/main/data/register_recipes.lua) does loop over the science items to generate things so that should be the issue.  I will try to confirm it this evening if I can pull away from the toddler before bed.  :-)

**Comment by nicolas-lang** [comment]
No reply, assuming it is fixed.

**Comment by OvermindDL1** [comment]
Haven't had a chance to take the server down yet, been up for a couple weeks now, probably time to do a full update of everything though, will message back if it doesn't fix it when next we restart and update the server, if nothing then it is good.  ^.^
