### ISSUE TITLE
Changelog format in mod is incorrect

### ISSUE THREAD

**Issue by OvermindDL1** [nicolas-lang/Factorio.SpaceScienceDelivery#8]
The changelog file is not parseable by factorio so it can't be displayed in game.  See these links for the format:

https://forums.factorio.com/viewtopic.php?t=67140
https://mods.factorio.com/mod/da-changelog-tools

**Comment by OvermindDL1** [comment]
I'm guessing it should have a line of dashes at the top maybe?  Unsure, but it's not showing in game.  ^.^;

**Comment by nicolas-lang** [comment]
yeah, that was missing... good catch.
